name: backendCI Pipeline

on:
  pull_request:
    branches:
      - main
      - frontend
      - backend
  push:
    branches:
      - frontend
      - backend

jobs:
  test:
  runs-on: ubuntu-latest

  steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Установка JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Шаг 3: Кэширование Gradle зависимостей для ускорения сборки
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Шаг 4: Сборка проекта и запуск тестов
    - name: Run tests
      run: ./gradlew test

    # Шаг 5: Запуск тестов и проверка покрытия
    - name: Run tests and check coverage
      run: ./gradlew check jacocoTestReport

    # Публикация HTML отчета о покрытии кода как артефакт
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: build/reports/jacoco/test/html